export const adminTypes = {
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  INITIALIZE_APP_Admin: "INITIALIZE_APP_Admin",
  LOAD_Admin_DATA: "LOAD_Admin_DATA",
  DELETE_Admin: "DELETE_Admin",
};

export const patientTypes = {
  FETCH_PATIENT_START: "FETCH_PATIENT_START",
  FETCH_PATIENT_SUCCESS: "FETCH_PATIENT_SUCCESS",
  FETCH_PATIENT_FAILURE: "FETCH_PATIENT_FAILURE",
  DELETE_PATIENT_SUCCESS: "DELETE_PATIENT_SUCCESS",
  DELETE_PATIENT_FAILURE: "DELETE_PATIENT_FAILURE",
  ADD_PATIENT_SUCCESS: "ADD_PATIENT_SUCCESS",
  ADD_PATIENT_FAILURE: "ADD_PATIENT_FAILURE",
  UPDATE_PATIENT_SUCCESS: "UPDATE_PATIENT_SUCCESS",
  UPDATE_PATIENT_FAILURE: "UPDATE_PATIENT_FAILURE",
};

export const hospitalTypes = {
  FETCH_HOSPITAL_START: "FETCH_HOSPITAL_START",
  FETCH_HOSPITAL_SUCCESS: "FETCH_HOSPITAL_SUCCESS",
  FETCH_HOSPITAL_FAILURE: "FETCH_HOSPITAL_FAILURE",
  DELETE_HOSPITAL_SUCCESS: "DELETE_HOSPITAL_SUCCESS",
  DELETE_HOSPITAL_FAILURE: "DELETE_HOSPITAL_FAILURE",
  ADD_HOSPITAL_SUCCESS: "ADD_HOSPITAL_SUCCESS",
  ADD_HOSPITAL_FAILURE: "ADD_HOSPITAL_FAILURE",
  UPDATE_HOSPITAL_SUCCESS: "UPDATE_HOSPITAL_SUCCESS",
  UPDATE_HOSPITAL_FAILURE: "UPDATE_HOSPITAL_FAILURE",
};

export const allAdminsTypes = {
  FETCH_ALLADMIN_START: "FETCH_ALLADMIN_START",
  FETCH_ALLADMIN_SUCCESS: "FETCH_ALLADMIN_SUCCESS",
  FETCH_ALLADMIN_FAILURE: "FETCH_ALLADMIN_FAILURE",
  DELETE_ALLADMIN_SUCCESS: "DELETE_ALLADMIN_SUCCESS",
  DELETE_ALLADMIN_FAILURE: "DELETE_ALLADMIN_FAILURE",
  ADD_ALLADMIN_SUCCESS: "ADD_ALLADMIN_SUCCESS",
  ADD_ALLADMIN_FAILURE: "ADD_ALLADMIN_FAILURE",
  UPDATE_ALLADMIN_SUCCESS: "UPDATE_ALLADMIN_SUCCESS",
  UPDATE_ALLADMIN_FAILURE: "UPDATE_ALLADMIN_FAILURE",
};

export const medicalTypes = {
  FETCH_RECORDS_START: "FETCH_RECORDS_START",
  FETCH_RECORDS_SUCCESS: "FETCH_RECORDS_SUCCESS",
  FETCH_RECORDS_FAILURE: "FETCH_RECORDS_FAILURE",
  UPDATE_RECORDS_SUCCESS: "UPDATE_RECORDS_SUCCESS",
  UPDATE_RECORDS_FAILURE: "UPDATE_RECORDS_FAILURE",
  DELETE_RECORDS_SUCCESS: "DELETE_RECORDS_SUCCESS",
  DELETE_RECORDS_FAILURE: "DELETE_RECORDS_FAILURE",
};

export const chartTypes = {
  FETCH_PATIENTSMONTHLY_START: "FETCH_PATIENTSMONTHLY_START",
  FETCH_PATIENTSMONTHLY_SUCCESS: "FETCH_PATIENTSMONTHLY_SUCCESS",
  FETCH_PATIENTSMONTHLY_FAILURE: "FETCH_PATIENTSMONTHLY_FAILURE",
  FETCH_HOSPITALSMONTHLY_START: "FETCH_HOSPITALSMONTHLY_START",
  FETCH_HOSPITALSMONTHLY_SUCCESS: "FETCH_HOSPITALSMONTHLY_SUCCESS",
  FETCH_HOSPITALSMONTHLY_FAILURE: "FETCH_HOSPITALSMONTHLY_FAILURE",
  FETCH_RECORDSMONTHLY_START: "FETCH_RECORDSMONTHLY_START",
  FETCH_RECORDSMONTHLY_SUCCESS: "FETCH_RECORDSMONTHLY_SUCCESS",
  FETCH_RECORDSMONTHLY_FAILURE: "FETCH_RECORDSMONTHLY_FAILURE",
};
